server {
    listen 80;
    server_name nakout.com www.nakout.com;
    root /var/www/certbot;
    index index.html;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
