server {
    listen 80;
    server_name nakout.com www.nakout.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name nakout.com www.nakout.com;

    ssl_certificate /etc/letsencrypt/live/nakout.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nakout.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}
