server {
    listen 80;
    server_name nakout.com www.nakout.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name nakout.com www.nakout.com;

    ssl_certificate /etc/letsencrypt/live/nakout.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nakout.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    server_name odootest.nakout.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name odootest.nakout.com;

    ssl_certificate /etc/letsencrypt/live/odootest.nakout.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/odootest.nakout.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;

    location / {
        proxy_pass http://host.docker.internal:8069;
        proxy_redirect off;
    }

    location /longpolling/poll {
        proxy_pass http://host.docker.internal:8072;
    }
}
